### ISSUE TITLE
Make API compatible with AsyncStorage

### ISSUE THREAD

**Issue by kacper-serewis** [candlefinance/cache#2]
Great library!

Only thing I am missing is the API compatibility with AsyncStorage for seamless replace.

For example, Supabase library expects storage object to have the following functions: `removeItem`, `setItem` and `getItem`.

Workaround for now is to create a wrapper function like this:

```ts
const wrappedCacheStore = {
  getItem: async (key: string) => {
    return await read(key);
  },
  setItem: async (key: string, value: string) => {
    await write(key, value);
  },
  removeItem: async (key: string) => {
    await remove(key);
  },
};
```

**Comment by gtokman** [comment]
That sounds good. I'm happy to accept a PR. You'd have to go into the `index.tsx` and export that type.
