### ISSUE TITLE
Property 'Storage' doesn't exist and [TypeError: Cannot read property 'read' of undefined]

### ISSUE THREAD

**Issue by kacper-serewis** [candlefinance/cache#3]
When importing package using `import Storage from '@candlefinance/cache', I'm getting the following errors:

`[TypeError: Cannot read property 'read' of undefined]`

`Property 'Storage' doesn't exist`

Library works only when functions are imported like this:
`import {read, write, remove} from '@candlefinance/cache';`

I prefer the first way of importing because 'read', 'write' and 'remove' are commonly used function names, which results in duplicates.

**Comment by gtokman** [comment]
Also, I agree! I don't have the bandwidth right now, but modifying `index.tsx` should be trivial.
